// Generated — OSChief cardinal dots tray icon (44x44 black on transparent, template mode)
// Central circle + 4 cardinal dots = meetings radiating from you
export const TRAY_ICON_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAYAAAAehFoBAAAAS0lEQVR42u3WMQ4AIAgEMP7/aVydjA4aJG1yszcoEgFARzlFYYUB+oy1XOSrsiVLlym8c2Ae5Pq9V7jKZPHozGELPGCBV9jHAfDWALxRfIRqUk1LAAAAAElFTkSuQmCC'
export const TRAY_ICON_RECORDING_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAYAAAAehFoBAAAAS0lEQVR42u3WMQ4AIAgEMP7/aVydjA4aJG1yszcoEgFARzlFYYUB+oy1XOSrsiVLlym8c2Ae5Pq9V7jKZPHozGELPGCBV9jHAfDWALxRfIRqUk1LAAAAAElFTkSuQmCC'
